In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
size = 100_000_000

#time

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]

end = time.time()
print(f"python list time = {end-start} seconds")

# numpy array
np_arr = np.array(py_list)
start = time.time()

#vectorization
sq_array = np_arr **2
end = time.time()
print(f"numpy list time = {end-start} seconds")

python list time = 11.620572805404663 seconds
numpy list time = 0.31112122535705566 seconds


In [11]:
# memory
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")


python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


#creating np array

In [16]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr),  arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,'prime'])
print(arr2, type(arr2), arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [13]:
# create nd arrays
arr1 = np.zeros((2,3))
print(arr1, arr1.shape)

#ones
arr2 = np.ones((4,3))
print(arr2, arr2.shape)

#full
arr3 = np.full((2,3), 20)
print(arr3, arr3.shape)

#eye
arr4 = np.eye((3))
print(arr4, arr4.shape)

#arange
arr5 = np.arange(0,11,2)
print(arr5, arr5.shape)

#linspace
arr6 = np.linspace(1, 100, 4)
print(arr6, arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[[20 20 20]
 [20 20 20]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [14]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [18]:
#indexing
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

# print(arr[0])
# print(arr[1])
print(arr2[1][1])

5


In [24]:
# multi dimensional arrays

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_cols = np.sum(arr2d, axis=0)
print(sum_of_cols)

sum_of_rows = np.sum(arr2d, axis=1)
print(sum_of_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [29]:
#3d arrays

arr3d = np.array([[[1,2],[3,4], [5,6]], [[7,8], [9, 10], [11, 12]]])
print(arr3d, arr3d.shape)

#indexing
print(arr3d[0, 1, 1])

#slicing
print(arr3d[:, 0, :])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]


In [31]:
# vectorization
arr = np.array([1,2,3,4,5])

print(arr ** 2)
print(arr + 5)

[ 1  4  9 16 25]
[ 6  7  8  9 10]


In [34]:
#broadcasting
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [38]:
#normalization
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
sd = np.std(arr)

print(mean)
print(sd)

normalized_arr = (arr-mean)/sd
print(normalized_arr)

2.5
1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
